<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE TVSCHEDULE [
  <!ELEMENT TVSCHEDULE (channel+)>
  <!ELEMENT channel (banner, day+)>
  <!ELEMENT banner (#PCDATA)>
  <!ELEMENT day (date, (holiday|programslot)+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT holiday (#PCDATA)>
  <!ELEMENT programslot (time, title, description?)>
  <!ELEMENT time (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
<!ATTLIST TVSCHEDULE name CDATA #REQUIRED>
<!ATTLIST channel chan CDATA #REQUIRED>
<!ATTLIST programslot vtr CDATA #IMPLIED>
<!ATTLIST title 
rating CDATA #implied
language CDATA #implied
>
]>

<TVSCHEDULE name="1st schedule">
  <channel chan="channel_1">
    <banner>Banner_1</banner>
    <day_1>
      <date>2023-09-11</date>
      <holiday>Christmas</holiday>
      <programslot vtr="123">
        <time>07:16</time>
        <title rating="PG-13" language="english">title_1</title>
        <description>Programslot for who knows how long</description>
      </programslot>
    </day_1>
  </channel>
  <channel chan="channel_2">
    <banner>Banner_2</banner>
    <day_>
      <date>2023-09-11</date>
      <holiday>Christmas</holiday>
      <programslot vtr="456">
        <time>07:16</time>
        <title rating="PG-18" language="nepali">title_1</title>
        <description>Programslot for who knows how long</description>
      </programslot>
    </day_2>
  </channel>
</TVSCHEDULE>
